## create a rolebinding

## k create rolebinding clothing-shop-rolebinding --role=clothing-shop-role --serviceaccount=clothing-shop-namespace:clothing-shop-serviceaccount --namespace=clothing-shop-namespace --dry-run=client -o yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clothing-shop-rolebinding
  namespace: clothing-shop-namespace
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: clothing-shop-role
subjects:
- kind: ServiceAccount
  name: clothing-shop-serviceaccount
  namespace: clothing-shop-namespace
