## create secret

## k create secret tls clothing-shop-testsecret-tls --cert=cert.crt --key=cert.key --namespace=clothing-shop-namespace --dry-run=client -o yaml

apiVersion: v1
kind: Secret
metadata:
  name: clothing-shop-testsecret-tls
  namespace: clothing-shop-namespace
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls
